baseurl: https://psychlablandingpage.netlify.app/
author: "Claudiu C. Papasteri"
languageCode: en-US
# title: Welcome
paginate: 5
theme: bulma
enableRobotsTXT: yes
googleAnalytics: ''
disqusShortname: ''
SectionPagesMenu: ''
params:
  # description: Sign up now to stay in touch with us
  # github: github
  hide_author: no
  images: []
  powered_by: 
  theme_variant: ''
  # twitter: twitter
  # youtube: "channel/UCosMp1GEG68ByDqFL_NlCZA"    # not implemented yet
  github: "ClaudiuPapasteri"

markup:
  goldmark:
    renderer:
      unsafe: true
      
# suggested by blogdown
ignoreFiles:
- \.Rmd$
- \.Rmarkdown$
- _cache$



