baseurl: https://psychlablandingpage.netlify.app/ 
languageCode: en-US
title: Welcome
paginate: 5
theme: bulma
enableRobotsTXT: yes
googleAnalytics: ''
disqusShortname: ''
SectionPagesMenu: main
params:
  description: Sign up to stay in touch
  # github: github
  hide_author: no
  images: []
  powered_by: 
  theme_variant: ''
  # twitter: twitter
  # youtube: "channel/UCosMp1GEG68ByDqFL_NlCZA"    # not implemented yet
  github: "ClaudiuPapasteri"
  
markup:
  goldmark:
    renderer:
      unsafe: true
      
# suggested by blogdown
ignoreFiles:
- \.Rmd$
- \.Rmarkdown$
- _cache$        
