baseurl = "https://psychlablandingpage.netlify.app/" # Controls base URL
author = "your name"
languageCode = "en-US" # Controls html lang attribute
title = "Welcome" # Homepage title and page title suffix
paginate = 5 # Number of posts to show before paginating
theme = "bulma" # to use as default theme

enableRobotsTXT = true # Suggested, it generates a robots.txt
googleAnalytics = "" # Optional, add tracking Id for analytics
disqusShortname = "" # Optional, add Disqus shortname for comments
SectionPagesMenu = "main" # Enable menu system for lazy bloggers

[params]
  theme_variant = "" # possible value for the theme_variant `cerulean,cosmo,cyborg,darkly,flatly,journal,litera,lumen,lux,materia,minty,pulse,sandstone,simplex,slate,solar,spacelab,superhero,united,yeti`
  description = "Sign up now to stay in touch with us" # Suggested, controls default description meta and landing page
  powered_by = ""   # Optional, controls name display on footer
  hide_author = false # Optional, set true to hide author name on posts
  images = [] # Suggested, controls default OpenGraph images controls author name display on meta tag
  github  = "github" # Optional, to display link to github account in menu bar
  twitter = "" # Optional, to display link to twitter account in menu bar


  